// Generated by CoffeeScript 1.8.0
(function() {
  var chai, expect, isCoffee;

  chai = require("chai");

  expect = chai.expect;

  isCoffee = require('./isCoffee');

  describe.only("main.coffee", function() {
    return it("should export all public classes", function() {
      var npmExports;
      if (isCoffee) {
        npmExports = require("../../src/main");
      } else {
        npmExports = require("../../lib/main");
      }
      expect(npmExports).to.be.an('object');
      expect(npmExports.SpaceJam).to.be.a('function');
      expect(npmExports.Meteor).to.be.a('function');
      return expect(npmExports.Phantomjs).to.be.a('function');
    });
  });

}).call(this);
