// Generated by CoffeeScript 1.8.0
(function() {
  var chai, expect;

  chai = require("chai");

  expect = chai.expect;

  describe("main.coffee", function() {
    return it("should export all public classes", function() {
      var npmExports;
      npmExports = require("../../src/main");
      expect(npmExports).to.be.an('object');
      expect(npmExports.SpaceJam).to.be.a('function');
      expect(npmExports.Meteor).to.be.a('function');
      return expect(npmExports.Phantomjs).to.be.a('function');
    });
  });

}).call(this);
