// Generated by CoffeeScript 1.9.1
(function() {
  var chai, expect, isCoffee;

  chai = require("chai");

  expect = chai.expect;

  isCoffee = require('./isCoffee');

  describe("main", function() {
    return it("should export all public classes", function() {
      var npmExports;
      if (isCoffee) {
        npmExports = require("../../src/main");
      } else {
        npmExports = require("../../lib/main");
      }
      expect(npmExports).to.be.an('object');
      expect(npmExports.Spacejam).to.be.a('function');
      expect(npmExports.Meteor).to.be.a('function');
      return expect(npmExports.Phantomjs).to.be.a('function');
    });
  });

}).call(this);
