// Generated by CoffeeScript 1.8.0
(function() {
  var Spacejam, chai, expect, isCoffee, path, sinon, sinonChai;

  chai = require("chai");

  expect = chai.expect;

  sinon = require("sinon");

  sinonChai = require("sinon-chai");

  chai.use(sinonChai);

  path = require("path");

  isCoffee = require('./isCoffee');

  if (isCoffee) {
    Spacejam = require('../../src/Spacejam');
  } else {
    Spacejam = require('../../lib/Spacejam');
  }

  describe("Spacejam", function() {
    var spacejam;
    this.timeout(60000);
    spacejam = null;
    before(function() {});
    beforeEach(function() {
      delete process.env.PORT;
      delete process.env.ROOT_URL;
      delete process.env.MONGO_URL;
      delete process.env.PACKAGE_DIRS;
      return spacejam = new Spacejam();
    });
    return afterEach(function() {
      return spacejam = null;
    });
  });

}).call(this);
