// Generated by CoffeeScript 1.8.0
(function() {
  var logLevelOpts;

  global.log = require('loglevel');

  logLevelOpts = require("rc")("spacejam", {
    "log-level": "info"
  });

  log.setLevel(logLevelOpts["log-level"]);

}).call(this);
