// Generated by CoffeeScript 1.8.0
(function() {
  global.Package = {
    description: null,
    describe: function(options) {
      return Package.description = options;
    },
    onUse: function(f) {},
    on_use: function(f) {},
    onTest: function(f) {},
    on_test: function(f) {},
    registerBuildPlugin: function(options) {},
    _transitional_registerBuildPlugin: function(options) {},
    includeTool: function() {}
  };

  global.Npm = {
    depends: function(_npmDependencies) {},
    strip: function(discards) {},
    require: function(name) {}
  };

  global.Cordova = {
    depends: function(_cordovaDependencies) {}
  };

}).call(this);
