// Generated by CoffeeScript 1.8.0
(function() {
  var Pipe;

  Pipe = (function() {
    function Pipe(stdout, stderr) {
      this.stdout = stdout;
      this.stderr = stderr;
      this.stdout.setEncoding("utf8");
      this.stderr.setEncoding("utf8");
      this.stdout.on("data", (function(_this) {
        return function(data) {
          return process.stdout.write(data);
        };
      })(this));
      this.stderr.on("data", (function(_this) {
        return function(data) {
          return process.stderr.write(data);
        };
      })(this));
    }

    return Pipe;

  })();

  module.exports = Pipe;

}).call(this);
